version: "3.8"
services:

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - worker

  worker:
    build: .
    command: /venv/bin/dramatiq bostongene.heavy_calc --verbose
    depends_on:
      - redis

  redis:
    image: "redis"
    # ports:
    #  - "6379:6379"
